### ISSUE TITLE
This package is incompatible with Server-side Rendering

### ISSUE THREAD

**Issue by mmmeff** [nathanbuchar/react-hook-thunk-reducer#13]
When I build my server-side renderer bundle with webpack, it is broken by this package's module output type of `amd`. This is because AMD format involves exporting the module as a self-invoking function that passes a direct reference on `window`, resulting in the following error:

`ReferenceError: window is not defined`

**Comment by nathanbuchar** [comment]
I believe this is addressed in #12 :)
