### ISSUE TITLE
dist file is huge

### ISSUE THREAD

**Issue by Athou** [nathanbuchar/react-hook-thunk-reducer#2]
The size of the file resulting from `npm run-script build` is 194kb.
This is also the case for the package on npmjs.org

I think React is bundled with the lib or something, is this the expected result?

**Comment by nathanbuchar** [comment]
Thanks for the callout. Yeah React is probably bundled by mistake, I'll take a look

**Comment by alflennik** [comment]
Yes! React should be a peerDependency, not a dependency.

**Comment by nathanbuchar** [comment]
Hey guys! Give `react-hook-thunk-reducer@next` a shot and let me know if it looks good to release :)
