### ISSUE TITLE
Init function run every time when state change. Expect only when init

### ISSUE THREAD

**Issue by zsc347** [nathanbuchar/react-hook-thunk-reducer#22]
https://github.com/nathanbuchar/react-hook-thunk-reducer/blob/ea5d0d5600adbb8046ffdd221a4d7526e00b6d3d/src/thunk-reducer.js#L26

How about change to 
```
const [hookState, setHookState] = useState(() => init(initialArg));
```

**Comment by spaceaardvark** [comment]
@zsc347 I'm curious as to 1) why React would run that init function every time, and 2) why your proposed fix would prevent it from doing so. Is this still a problem for you? If so, can you provide some additional context?

**Comment by zsc347** [comment]
@spaceaardvark 
> 1) why React would run that init function every time

As for a demo
https://jsfiddle.net/zsc347/63x2d9c7/
Every time when state change, component will render and `init` function will be triggered.

> 2)  why your proposed fix would prevent it from doing so

`useState` accept a function param which will only trigger once for initilaize state.
```
const [hookState, setHookState] = useState(() => init(initialArg));
```
then `init` inside it will only be triggered one time for provide an initilail state.
