### ISSUE TITLE
Does not work as documented when installed from NPM.

### ISSUE THREAD

**Issue by alflennik** [nathanbuchar/react-hook-thunk-reducer#5]
I got the following error when following the instructions in the docs.

When I manually copied the hook from the `src` folder in the repo and imported that instead, it worked.

Line that failed:

```js
const [state, dispatch] = useThunkReducer(reducer, initialState);
```

The error:
```
Uncaught TypeError: react_hook_thunk_reducer__WEBPACK_IMPORTED_MODULE_2___default is not a function or its return value is not iterable
    at myFile (myFile.js:8)
    at myFile2 (myFile.story.jsx:45)
    at renderWithHooks (react-dom.development.js:12939)
    at mountIndeterminateComponent (react-dom.development.js:15021)
    at beginWork (react-dom.development.js:15626)
    at performUnitOfWork (react-dom.development.js:19313)
    at workLoop (react-dom.development.js:19353)
    at HTMLUnknownElement.callCallback (react-dom.development.js:150)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:200)
    at invokeGuardedCallback (react-dom.development.js:257)
```

**Comment by nathanbuchar** [comment]
Yeah I've noticed this as well, thanks for reporting. Hoping to look more into this module soon

**Comment by nathanbuchar** [comment]
Give `react-hook-thunk-reducer@next` a shot and let me know if this solves it :)

**Comment by halfbug** [comment]
i have the same issue even after installation of react-hook-thunk-reducer@next

`TypeError: react_hook_thunk_reducer__WEBPACK_IMPORTED_MODULE_15___default(...) is not a function`

**Comment by nathanbuchar** [comment]
Which version of React and ReactDOM are you using? Which module bundler are you using to compile your application (Webpack, rollup, etc.)? Can I see how in code you're importing and using `react-hook-thunk-reducer`?

**Comment by alflennik** [comment]
It's working for me. Thank @nathanbuchar for the effort. 

I installed react-hook-thunk-reducer@latest (^0.1.0-beta.0) and then just followed the docs.

@halfbug Don't know if it will help, but here's my setup:

package.json

```json
  "dependencies": {
    "react-hook-thunk-reducer": "^0.1.0-beta.0",
  },
```

```js
import useThunkReducer from "react-hook-thunk-reducer";

const useMyHook = () => {
  const initialState = {};
  const [state, dispatch] = useThunkReducer(myReducer, initialState);
  const actions = myActions(dispatch);
  return [state, actions];
};
```

```

**Comment by nathanbuchar** [comment]
Archiving. If you continue to experience problems, please let me know.
